title: "AC:NH Beginner's Guide"
remote_theme: pdmosses/just-the-docs@callouts
color_scheme: custom
plugins:
  - jekyll-feed
  - jekyll-remote-theme
description: Fan-made FAQ for AC:NH
permalink: pretty #make url pretty
back_to_top: true
back_to_top_text: "Back to top" #add back to top as footer
last_edit_timestamp: true
last_edit_time_format: "%b %e %Y at %I:%M %p" #added this because back to top didn't show up without this, probably don't need it
search.button: true
kramdown:
  input: GFM
aux_links:
  <button class="btn js-toggle-dark-mode">Theme Toggle</button>
  <script>
    const toggleDarkMode = document.querySelector('.js-toggle-dark-mode');
    jtd.addEvent(toggleDarkMode, 'click', function()
    {
      if (jtd.getTheme() === 'custom') 
      {
        jtd.setTheme('light');
        toggleDarkMode.textContent = 'Toggle to Dark';
      }
      else 
      {
        jtd.setTheme('custom');
        toggleDarkMode.textContent = 'Toggle to light';
      }
    });
  </script>